# Exercícios NumPy  

Agora que aprendemos sobre NumPy, vamos testar seu conhecimento. Começaremos com algumas tarefas simples, para depois entrarmos nas perguntas mais complicadas.

#### Importe NumPy como np

In [1]:
import numpy as np
import pandas as pd

#### Crie uma matriz de 10 zeros

In [ ]:
lista3 = np.zeros(10)
lista3 + 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crie uma matriz de 10 ones

In [ ]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Crie uma matriz de 10 cincos

In [ ]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Crie um array de inteiros de 10 até 50

In [3]:
lista4 = np.arange(10,51)
ultimo = len(lista4)
lista4[ultimo]


IndexError: ignored

#### Crie um array dos numeros pares de 10 até 50

[50,
 48,
 46,
 44,
 42,
 40,
 38,
 36,
 34,
 32,
 30,
 28,
 26,
 24,
 22,
 20,
 18,
 16,
 14,
 12,
 10]

#### Criei uma matriz 3x3 com valores variando de 0 até 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crie uma matriz identidade 3x3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy para gerar números aleatórios entre 0 e 1

array([ 0.42829726])

#### Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Crie a seguinte matriz:

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Indexação Numpy e Seleção

Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# ESCREVE O CÓDIGO AQUI QUE REPRODUZA A SAÍDA DA CÉLULA ABAIXO

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# ESCREVE O CÓDIGO AQUI QUE REPRODUZA A SAÍDA DA CÉLULA ABAIXO

20

In [ ]:
# ESCREVE O CÓDIGO AQUI QUE REPRODUZA A SAÍDA DA CÉLULA ABAIXO

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# ESCREVE O CÓDIGO AQUI QUE REPRODUZA A SAÍDA DA CÉLULA ABAIXO

array([21, 22, 23, 24, 25])

In [ ]:
# ESCREVE O CÓDIGO AQUI QUE REPRODUZA A SAÍDA DA CÉLULA ABAIXO

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Agora faça o seguinte

#### Obter a soma de todos os valores no "mat"

325

#### Obter o desvio padrão dos valores em mat

7.2111025509279782

#### Obter a soma de todas as colunas em mat

array([55, 60, 65, 70, 75])